---
name: Checks

#trigger
on: [push]

jobs:
  test-lint: #id of new job called test lint so that it can be refered
    name: Test and Lint #human friendly name for githb actions interface
    runs-on: ubuntu-20.04 # OS for running job
    steps: #first step of our job  to login to dockerhub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
           username: ${{ secrets.DOCKERHUB_USER }}
           passsword: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout  # checks our code out
        uses: actions/checkout@v2
      - name: Test   #run unit tests
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint  #run linting
        run: docker-compose run --rm app sh -c "flake8"